Вывод error

customError удовлетворяет интерфейсу error, но err при присвоении имеет тип  *customError и !=nil
